"""
MuniFix AI Engine — categorisation, urgency scoring, and report generation.
"""
import re
import json
import structlog
from typing import Optional
from app.core.config import settings
from openai import AsyncOpenAI

log = structlog.get_logger()
client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY) if settings.OPENAI_API_KEY else None


CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "water_leak": [
        "leak", "burst pipe", "water running", "overflowing", "broken tap",
        "water outage", "no water", "pipe burst",
    ],
    "electricity_fault": [
        "electricity", "power outage", "no power", "load shedding fault",
        "transformer", "sparks", "cable fault", "substation", "trip",
    ],
    "pothole": [
        "pothole", "road damaged", "tar cracked", "sinkhole", "road collapsed",
        "damaged road", "bad road",
    ],
    "sewage": [
        "sewage", "sewer", "toilet blocked", "drain blocked", "manhole",
        "waste water", "foul smell", "raw sewage",
    ],
    "illegal_dumping": [
        "illegal dump", "rubbish", "trash", "garbage", "waste dumped",
        "litter", "refuse",
    ],
    "streetlight": [
        "streetlight", "street light", "lamp post", "light pole", "no lighting",
        "dark street",
    ],
    "infrastructure": [
        "building", "unsafe structure", "collapsing", "bridge", "cracked wall",
        "dangerous",
    ],
}

DEPARTMENTS: dict[str, str] = {
    "water_leak": "Water & Sanitation Department",
    "electricity_fault": "Electricity / City Power Department",
    "pothole": "Roads & Transport Department",
    "sewage": "Sanitation & Sewer Maintenance",
    "illegal_dumping": "Waste Management Department",
    "streetlight": "Electrical Maintenance / Public Lighting",
    "infrastructure": "Infrastructure & Built Environment Department",
    "general": "General Municipal Services",
}

URGENCY_HIGH = [
    "burst", "flood", "danger", "sparks", "fire", "explosion",
    "collapse", "sewage overflowing", "raw sewage",
]
URGENCY_MEDIUM = [
    "leaking", "blocked", "not working", "broken", "cracked", "dark",
]


def _sanitize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def detect_category(description: str) -> str:
    text = description.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if kw in text:
                return category
    return "general"


def compute_urgency(description: str) -> int:
    text = description.lower()
    if any(word in text for word in URGENCY_HIGH):
        return 5
    if any(word in text for word in URGENCY_MEDIUM):
        return 3
    return 2


def generate_report(
    description: str,
    location: Optional[str] = None,
    municipality: Optional[str] = None,
) -> dict:
    description = _sanitize(description)
    location = _sanitize(location) if location else "Not provided"
    municipality = _sanitize(municipality) if municipality else "Not provided"

    category = detect_category(description)
    urgency = compute_urgency(description)
    department = DEPARTMENTS.get(category, DEPARTMENTS["general"])

    report_text = f"""MUNICIPAL SERVICE COMPLAINT REPORT
South African Local Government Service Delivery

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ISSUE CATEGORY    : {category.replace("_", " ").title()}
URGENCY LEVEL     : {urgency}/5 {'🔴 CRITICAL' if urgency == 5 else '🟡 MODERATE' if urgency == 3 else '🟢 LOW'}
LOCATION          : {location}
MUNICIPALITY      : {municipality}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROBLEM DESCRIPTION:
{description}

IMPACT ASSESSMENT:
This issue poses a risk to public health, safety, and service delivery
as guaranteed under the South African Constitution (Section 152).

REQUESTED ACTION:
Please dispatch the relevant technical team to inspect and resolve
this issue within the prescribed service delivery timeframe.

RESPONSIBLE DEPARTMENT:
{department}

ESCALATION PATH (if unresolved within 5 business days):
1. Contact your Ward Councillor
2. Submit to the provincial MEC for Cooperative Governance
3. Log a complaint with the Public Protector (www.publicprotector.org)
4. Submit via Presidential Hotline: 17737

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by: MuniFix AI — South African Civic Service Platform
Report Reference: AUTO-{municipality[:3].upper() if municipality != 'Not provided' else 'GEN'}-{urgency}{len(description) % 9999:04d}
""".strip()

    return {
        "category": category,
        "urgency_score": urgency,
        "suggested_department": department,
        "generated_report": report_text,
    }


async def generate_report_ai(
    description: str,
    location: Optional[str] = None,
    municipality: Optional[str] = None,
    ward: Optional[str] = None,
    households: int = 1,
    severity: int = 2,
    language: str = "English"
) -> dict:
    """
    Advanced AI report generation with professional rewriting and translation.
    """
    category = detect_category(description)
    department = DEPARTMENTS.get(category, DEPARTMENTS["general"])
    urgency = max(severity, compute_urgency(description))

    if not client:
        # Fallback to rule-based template
        report = generate_report(description, location, municipality)
        return {**report, "language": "English", "ai_optimized": False}

    system_prompt = f"""You are the MuniFix AI Professional Complaint Writer.
Your goal is to turn a citizen's raw complaint into a high-impact, formal municipal service letter.

CONTEXT:
- Authority: South African Local Government (Section 152 of the Constitution)
- Category: {category}
- Target Department: {department}
- Language: {language}
- Severity: {urgency}/5

STRICT RULES:
1. Use professional, legalistic municipal language (e.g., 'formal notification', 'service delivery failure', 'mitigate risk').
2. Cite Section 152 of the South African Constitution.
3. Be firm but polite.
4. Include a clear reference number placeholder (REF-XXXX).
5. Output ONLY the polished report text in {language}.
"""

    user_input = f"""
Complaint: {description}
Location: {location}
Municipality: {municipality}
Ward: {ward}
Households Affected: {households}
Severity: {urgency}/5
"""

    try:
        response = await client.chat.completions.create(
            model=settings.OPENAI_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input},
            ],
            temperature=0.3,
            max_tokens=1500,
        )
        polished_text = response.choices[0].message.content.strip()
        
        return {
            "category": category,
            "urgency_score": urgency,
            "suggested_department": department,
            "generated_report": polished_text,
            "language": language,
            "ai_optimized": True
        }
    except Exception as e:
        log.error("AI report generation failed", error=str(e))
        report = generate_report(description, location, municipality)
        return {**report, "language": "English", "ai_optimized": False}
