import jsPDF from "jspdf";
import "jspdf-autotable";
import { format } from "date-fns";

export const generateTaxPDF = (summary: any, history: any[], shopName: string) => {
  const doc = new jsPDF() as any;
  const timestamp = format(new Date(), "yyyy-MM-dd HH:mm");

  // Header
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // Blue
  doc.text("SpazaAI TaxMate - SARS Report", 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${timestamp}`, 14, 30);
  doc.text(`Shop: ${shopName}`, 14, 35);
  doc.text(`Reference: TAX-${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 14, 40);

  // Summary Box
  doc.setDrawColor(200);
  doc.setFillColor(249, 250, 251);
  doc.rect(14, 50, 182, 40, "F");
  
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("TAX YEAR SUMMARY (2025)", 20, 60);
  
  doc.setFontSize(10);
  doc.text(`Total Turnover (YTD): R ${summary.total_turnover.toLocaleString()}`, 20, 70);
  doc.text(`Estimated Tax Payable: R ${summary.estimated_tax.toLocaleString()}`, 20, 75);
  doc.text(`Current Bracket: ${summary.current_bracket?.rate_percentage || 0}%`, 20, 80);
  doc.text(`Projected Year End: R ${summary.projected_turnover.toLocaleString()}`, 20, 85);

  // Table
  doc.autoTable({
    startY: 100,
    head: [["Date", "Category", "Notes", "Amount (ZAR)"]],
    body: history.map(h => [
      format(new Date(h.entry_date), "yyyy-MM-dd"),
      h.category,
      h.notes || "-",
      `R ${h.amount.toLocaleString()}`
    ]),
    theme: "striped",
    headStyles: { fillColor: [37, 99, 235] },
  });

  // Footer / Disclaimer
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Disclaimer: This report is an estimate generated by SpazaAI TaxMate. Please verify with a certified SARS tax practitioner.", 14, finalY);
  doc.text("Official SARS Turnover Tax requirements (March-February cycle) were applied to these calculations.", 14, finalY + 5);

  // Signatures
  doc.line(14, finalY + 30, 80, finalY + 30);
  doc.text("Shop Owner Signature", 14, finalY + 35);

  doc.line(120, finalY + 30, 186, finalY + 30);
  doc.text("Date of Verification", 120, finalY + 35);

  doc.save(`SARS_Turnover_Tax_${shopName.replace(/\s+/g, "_")}_2025.pdf`);
};
